import type { Metadata } from "next";
import "./../globals.css";
import AdminNav from "@/components/admin/AdminNav";

export const metadata: Metadata = {
  title: "Chanuka Senevirathne",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col md:flex-row min-h-screen bg-[#0A0F1C] text-white">
        {/* Nav on LEFT */}
        <AdminNav />

        <main className="flex-1 p-6 md:pl-20">{children}</main>
      </body>
    </html>
  );
}